/* OSGiliath — OpenSceneGraph fork. See LICENSE.txt.
 * GPU-based skeletal skinning using bone matrix uniforms.
 * Uploads bone palette to shaders for vertex deformation.
 */
#pragma once

#include <osg/core/Inherit.hpp>
#include <osg/geometry/Array.hpp>
#include <osg/maths/mat4.hpp>
#include <osgAnimation/core/Export.hpp>
#include <osgAnimation/skeletal/Bone.hpp>
#include <osgAnimation/skeletal/RigTransform.hpp>
#include <osgAnimation/skeletal/VertexInfluence.hpp>

#define RIGTRANSHW_DEFAULT_FIRST_VERTATTRIB_TARGETTED 11

namespace osgAnimation
{

    class RigGeometry;

    /// This class manage format for hardware skinning
    class OSGANIMATION_EXPORT RigTransformHardware
        : public osg::Inherit<RigTransform, RigTransformHardware>
    {
        public:

            RigTransformHardware();

            RigTransformHardware( const RigTransformHardware& rth,
                                  const osg::CopyOp&          copyop );

            OSG_REGISTER_TYPE( osgAnimation,
                               RigTransformHardware )

            typedef std::vector<osg::ref_ptr<osg::Vec4Array>> BoneWeightAttribList;
            typedef std::vector<osg::ref_ptr<Bone>>           BonePalette;
            typedef std::map<std::string, unsigned int>       BoneNamePaletteIndex;
            typedef std::vector<osg::dmat4>                   MatrixPalette;

            /// set the first Vertex Attribute Array index of the rig generated by this
            /// technic (default:11)
            void
            setFirstVertexAttributeTarget( unsigned int i )
            {
                _minAttribIndex = i;
            }

            unsigned int
            getFirstVertexAttributeTarget() const
            {
                return _minAttribIndex;
            }

            void
            setShader( osg::Shader* shader )
            {
                _shader = shader;
            }

            const osg::Shader*
            getShader() const
            {
                return _shader.get();
            }

            osg::Shader*
            getShader()
            {
                return _shader.get();
            }

            osg::Vec4Array*
            getVertexAttrib( unsigned int index );

            unsigned int
            getNumVertexAttrib() const
            {
                return static_cast<unsigned int>( _boneWeightAttribArrays.size() );
            }

            const unsigned int&
            getNumBonesPerVertex() const
            {
                return _bonesPerVertex;
            }

            const unsigned int&
            getNumVertexes() const
            {
                return _nbVertices;
            }

            const BoneNamePaletteIndex&
            getBoneNameToPalette()
            {
                return _boneNameToPalette;
            }

            const BonePalette&
            getBonePalette()
            {
                return _bonePalette;
            }

            osg::Uniform*
            getMatrixPaletteUniform()
            {
                return _uniformMatrixPalette.get();
            }

            void
            computeMatrixPaletteUniform(
                const osg::dmat4& transformFromSkeletonToGeometry,
                const osg::dmat4& invTransformFromSkeletonToGeometry
            );

            // update rig if needed
            virtual void
            operator()( RigGeometry& );

            // init/reset animations data
            virtual bool
            prepareData( RigGeometry& );

        protected:

            unsigned int               _bonesPerVertex;
            unsigned int               _nbVertices;

            BonePalette                _bonePalette;
            BoneNamePaletteIndex       _boneNameToPalette;
            BoneWeightAttribList       _boneWeightAttribArrays;
            osg::ref_ptr<osg::Uniform> _uniformMatrixPalette;
            osg::ref_ptr<osg::Shader>  _shader;

            bool                       _needInit;
            unsigned int               _minAttribIndex;
            bool
            buildPalette( const BoneMap&     boneMap,
                          const RigGeometry& rig );

            // on first update
            virtual bool
                                         init( RigGeometry& );

            std::vector<IndexWeightList> _perVertexInfluences;
    };

}
