char shadergen_vert[] = "#version 460 core\n"
                        "// ShaderGen shader\n"
                        "layout(location = 0) in vec4 osg_Vertex;\n"
                        "layout(location = 2) in vec3 osg_Normal;\n"
                        "layout(location = 3) in vec4 osg_Color;\n"
                        "layout(location = 8) in vec4 osg_MultiTexCoord0;\n"
                        "uniform mat4 osg_ModelViewProjectionMatrix;\n"
                        "uniform mat4 osg_ModelViewMatrix;\n"
                        "uniform mat3 osg_NormalMatrix;\n"
                        "\n"
                        "#pragma import_defines(OSG_LIGHTING, OSG_TEXTURE_2D, OSG_TEXGEN_SPHERE_MAP)\n"
                        "\n"
                        "\n"
                        "#ifdef OSG_LIGHTING\n"
                        "struct osg_LightSourceParameters {\n"
                        "    vec4 ambient;\n"
                        "    vec4 diffuse;\n"
                        "    vec4 specular;\n"
                        "    vec4 position;\n"
                        "    vec3 spotDirection;\n"
                        "    float spotExponent;\n"
                        "    float spotCutoff;\n"
                        "    float spotCosCutoff;\n"
                        "    float constantAttenuation;\n"
                        "    float linearAttenuation;\n"
                        "    float quadraticAttenuation;\n"
                        "};\n"
                        "uniform osg_LightSourceParameters osg_LightSource;\n"
                        "\n"
                        "struct osg_MaterialParameters {\n"
                        "    vec4 ambient;\n"
                        "    vec4 diffuse;\n"
                        "    vec4 specular;\n"
                        "    vec4 emission;\n"
                        "    float shininess;\n"
                        "};\n"
                        "uniform osg_MaterialParameters osg_FrontMaterial;\n"
                        "uniform float osg_ColorMaterial;\n"
                        "uniform vec4 osg_LightModel_ambient;\n"
                        "\n"
                        "void computeLight( vec3 normal, vec3 eyeVertex, inout vec4 color )\n"
                        "{\n"
                        "    vec3 rawNormal = osg_NormalMatrix * normal;\n"
                        "    float normalLen = length(rawNormal);\n"
                        "    vec3 L;\n"
                        "    float attenuation = 1.0;\n"
                        "    if (osg_LightSource.position.w == 0.0) {\n"
                        "        L = normalize(osg_LightSource.position.xyz);\n"
                        "    } else {\n"
                        "        vec3 lightDir = osg_LightSource.position.xyz - eyeVertex;\n"
                        "        float d = length(lightDir);\n"
                        "        L = lightDir / d;\n"
                        "        attenuation = 1.0 / (osg_LightSource.constantAttenuation +\n"
                        "            osg_LightSource.linearAttenuation * d +\n"
                        "            osg_LightSource.quadraticAttenuation * d * d);\n"
                        "        if (osg_LightSource.spotCutoff < 180.0) {\n"
                        "            float spotDot = dot(-L, normalize(osg_LightSource.spotDirection));\n"
                        "            if (spotDot >= osg_LightSource.spotCosCutoff)\n"
                        "                attenuation *= pow(spotDot, osg_LightSource.spotExponent);\n"
                        "            else\n"
                        "                attenuation = 0.0;\n"
                        "        }\n"
                        "    }\n"
                        "    // When no normal array is provided, osg_Normal is (0,0,0).\n"
                        "    // Use NdotL=1.0 for full illumination matching legacy behavior.\n"
                        "    float NdotL = (normalLen > 0.001)\n"
                        "        ? max(0.0, dot(rawNormal / normalLen, L))\n"
                        "        : 1.0;\n"
                        "\n"
                        "    // GL_COLOR_MATERIAL emulation\n"
                        "    vec4 matDiffuse = mix(osg_FrontMaterial.diffuse, color, osg_ColorMaterial);\n"
                        "    vec4 matAmbient = mix(osg_FrontMaterial.ambient, color, osg_ColorMaterial);\n"
                        "\n"
                        "    color = osg_FrontMaterial.emission +\n"
                        "            matAmbient * (osg_LightModel_ambient + osg_LightSource.ambient) +\n"
                        "            attenuation * osg_LightSource.diffuse * matDiffuse * NdotL;\n"
                        "\n"
                        "    if (normalLen > 0.001) {\n"
                        "        vec3 n = rawNormal / normalLen;\n"
                        "        vec3 V = (osg_LightSource.position.w == 0.0) ? vec3(0.0, 0.0, 1.0) : normalize(-eyeVertex);\n"
                        "        vec3 halfVector = normalize(L + V);\n"
                        "        float NdotHV = max(0.0, dot(n, halfVector));\n"
                        "        if ( NdotL * NdotHV > 0.0 )\n"
                        "            color += attenuation * osg_LightSource.specular * osg_FrontMaterial.specular * pow( NdotHV, osg_FrontMaterial.shininess );\n"
                        "    }\n"
                        "}\n"
                        "#endif // OSG_LIGHTING\n"
                        "\n"
                        "out vec4 vertexColor;\n"
                        "out vec4 texCoord_0;\n"
                        "\n"
                        "void main()\n"
                        "{\n"
                        "  gl_Position = osg_ModelViewProjectionMatrix * osg_Vertex;\n"
                        "\n"
                        "#if defined(OSG_TEXGEN_SPHERE_MAP)\n"
                        "  { vec3 u = normalize((osg_ModelViewMatrix * osg_Vertex).xyz);\n"
                        "    vec3 n = normalize(osg_NormalMatrix * osg_Normal);\n"
                        "    vec3 r = reflect(u, n);\n"
                        "    float m = 2.0 * sqrt(r.x*r.x + r.y*r.y + (r.z+1.0)*(r.z+1.0));\n"
                        "    texCoord_0 = vec4(r.x/m + 0.5, r.y/m + 0.5, 0.0, 1.0); }\n"
                        "#elif defined(OSG_TEXTURE_2D)\n"
                        "  texCoord_0 = osg_MultiTexCoord0;\n"
                        "#endif\n"
                        "\n"
                        "  vertexColor = osg_Color;\n"
                        "\n"
                        "#if defined(OSG_LIGHTING)\n"
                        "    computeLight(osg_Normal, (osg_ModelViewMatrix * osg_Vertex).xyz, vertexColor);\n"
                        "#endif\n"
                        "}\n"
                        "\n";
