char shadergen_frag[] = "#version 460 core\n"
                        "// ShaderGen shader\n"
                        "\n"
                        "#pragma import_defines(OSG_TEXTURE_2D)\n"
                        "\n"
                        "in vec4 vertexColor;\n"
                        "in vec4 texCoord_0;\n"
                        "out vec4 fragColor;\n"
                        "\n"
                        "#if defined(OSG_TEXTURE_2D)\n"
                        "uniform sampler2D diffuseMap;\n"
                        "#endif\n"
                        "\n"
                        "void main()\n"
                        "{\n"
                        "  vec4 color = vertexColor;\n"
                        "\n"
                        "#if defined(OSG_TEXTURE_2D)\n"
                        "  color = color * texture(diffuseMap, texCoord_0.st);\n"
                        "#endif\n"
                        "\n"
                        "  fragColor = color;\n"
                        "}\n"
                        "\n";
