char lighting_vert[] = "#pragma requires(LIGHTING)\n"
                       "\n"
                       "uniform mat3 osg_NormalMatrix;\n"
                       "\n"
                       "struct osg_LightSourceParameters {\n"
                       "    vec4 ambient;\n"
                       "    vec4 diffuse;\n"
                       "    vec4 specular;\n"
                       "    vec4 position;\n"
                       "    vec3 spotDirection;\n"
                       "    float spotExponent;\n"
                       "    float spotCutoff;\n"
                       "    float spotCosCutoff;\n"
                       "    float constantAttenuation;\n"
                       "    float linearAttenuation;\n"
                       "    float quadraticAttenuation;\n"
                       "};\n"
                       "uniform osg_LightSourceParameters osg_LightSource;\n"
                       "\n"
                       "struct osg_MaterialParameters {\n"
                       "    vec4 ambient;\n"
                       "    vec4 diffuse;\n"
                       "    vec4 specular;\n"
                       "    vec4 emission;\n"
                       "    float shininess;\n"
                       "};\n"
                       "uniform osg_MaterialParameters osg_FrontMaterial;\n"
                       "\n"
                       "void directionalLight( vec3 normal, inout vec4 color )\n"
                       "{\n"
                       "    vec3 n = normalize(osg_NormalMatrix * normal);\n"
                       "\n"
                       "    float NdotL = dot( n, normalize(osg_LightSource.position.xyz) );\n"
                       "    NdotL = max( 0.0, NdotL );\n"
                       "\n"
                       "    vec3 halfVector = normalize(normalize(osg_LightSource.position.xyz) + vec3(0.0, 0.0, 1.0));\n"
                       "    float NdotHV = dot( n, halfVector );\n"
                       "    NdotHV = max( 0.0, NdotHV );\n"
                       "\n"
                       "    color *= osg_LightSource.ambient +\n"
                       "             osg_LightSource.diffuse * NdotL;\n"
                       "}\n"
                       "\n";
