/* OSGiliath — OpenSceneGraph fork. See LICENSE.txt.
 * Abstract manipulation command generated by draggers.
 * Carries transform delta (translation, rotation, scale).
 */
// osgManipulator - Copyright (C) 2007 Fugro-Jason B.V.

#pragma once

#include <osg/maths/compat.hpp>
#include <osg/maths/plane.hpp>
#include <osg/maths/vec2.hpp>
#include <osg/traversal/LineSegment.hpp>
#include <osgManipulator/Constraint.hpp>
#include <vector>

namespace osgManipulator
{

    /** Base class for motion commands that are generated by draggers. */
    class OSGMANIPULATOR_EXPORT MotionCommand : public osg::Referenced
    {
        public:

            /**
             * Motion command are based on click-drag-release actions. So each
             * command needs to indicate which stage of the motion the command
             * represents.
             */
            enum Stage
            {
                NONE,
                /** Click or pick start. */
                START,
                /** Drag or pick move. */
                MOVE,
                /** Release or pick finish. */
                FINISH
            };

            MotionCommand();

            /** create a MotionCommand that is the inverse of this command, and if
             * applied will undo this commands changes. */
            virtual MotionCommand*
            createCommandInverse() = 0;

            /**
             * Gets the matrix for transforming the object being dragged. This matrix is
             * in the command's coordinate systems.
             */
            virtual osg::dmat4
            getMotionMatrix() const = 0;

            virtual void
            accept( const Constraint& constraint )
            {
                constraint.constrain( *this );
            }

            virtual void
            accept( DraggerCallback& callback )
            {
                callback.receive( *this );
            }

            /**
             * Sets the matrix for transforming the command's local coordinate
             * system to the world/object coordinate system.
             */
            void
            setLocalToWorldAndWorldToLocal( const osg::dmat4& localToWorld,
                                            const osg::dmat4& worldToLocal )
            {
                _localToWorld = localToWorld;
                _worldToLocal = worldToLocal;
            }

            /**
             * Gets the matrix for transforming the command's local coordinate
             * system to the world/object coordinate system.
             */
            inline const osg::dmat4&
            getLocalToWorld() const
            {
                return _localToWorld;
            }

            /**
             * Gets the matrix for transforming the command's world/object
             * coordinate system to the command's local coordinate system.
             */
            inline const osg::dmat4&
            getWorldToLocal() const
            {
                return _worldToLocal;
            }

            void
            setStage( const Stage s )
            {
                _stage = s;
            }

            Stage
            getStage() const
            {
                return _stage;
            }

        protected:

            virtual ~MotionCommand();

        private:

            osg::dmat4 _localToWorld;
            osg::dmat4 _worldToLocal;

            Stage      _stage;
    };

    /**
     * Command for translating in a line.
     */
    class OSGMANIPULATOR_EXPORT TranslateInLineCommand : public MotionCommand
    {
        public:

            TranslateInLineCommand();

            TranslateInLineCommand( const osg::LineSegment::vec_type& s,
                                    const osg::LineSegment::vec_type& e );

            virtual void
            accept( const Constraint& constraint )
            {
                constraint.constrain( *this );
            }

            virtual void
            accept( DraggerCallback& callback )
            {
                callback.receive( *this );
            }

            virtual MotionCommand*
            createCommandInverse();

            inline void
            setLine( const osg::LineSegment::vec_type& s,
                     const osg::LineSegment::vec_type& e )
            {
                _line->start() = s;
                _line->end()   = e;
            }

            inline const osg::LineSegment::vec_type&
            getLineStart() const
            {
                return _line->start();
            }

            inline const osg::LineSegment::vec_type&
            getLineEnd() const
            {
                return _line->end();
            }

            inline void
            setTranslation( const osg::dvec3& t )
            {
                _translation = t;
            }

            inline const osg::dvec3&
            getTranslation() const
            {
                return _translation;
            }

            virtual osg::dmat4
            getMotionMatrix() const
            {
                return osg::translate( _translation );
            }

        protected:

            virtual ~TranslateInLineCommand();

        private:

            osg::ref_ptr<osg::LineSegment> _line;
            osg::dvec3                     _translation;
    };

    /**
     * Command for translating in a plane.
     */
    class OSGMANIPULATOR_EXPORT TranslateInPlaneCommand : public MotionCommand
    {
        public:

            TranslateInPlaneCommand();

            TranslateInPlaneCommand( const osg::Plane& plane );

            virtual void
            accept( const Constraint& constraint )
            {
                constraint.constrain( *this );
            }

            virtual void
            accept( DraggerCallback& callback )
            {
                callback.receive( *this );
            }

            virtual MotionCommand*
            createCommandInverse();

            inline void
            setPlane( const osg::Plane& plane )
            {
                _plane = plane;
            }

            inline const osg::Plane&
            getPlane() const
            {
                return _plane;
            }

            inline void
            setTranslation( const osg::dvec3& t )
            {
                _translation = t;
            }

            inline const osg::dvec3&
            getTranslation() const
            {
                return _translation;
            }

            /** ReferencePoint is used only for snapping. */
            inline void
            setReferencePoint( const osg::dvec3& rp )
            {
                _referencePoint = rp;
            }

            inline const osg::dvec3&
            getReferencePoint() const
            {
                return _referencePoint;
            }

            virtual osg::dmat4
            getMotionMatrix() const
            {
                return osg::translate( _translation );
            }

        protected:

            virtual ~TranslateInPlaneCommand();

        private:

            osg::Plane _plane;
            osg::dvec3 _translation;
            osg::dvec3 _referencePoint;
    };

    /**
     * Command for 1D scaling.
     */
    class OSGMANIPULATOR_EXPORT Scale1DCommand : public MotionCommand
    {
        public:

            Scale1DCommand();

            virtual void
            accept( const Constraint& constraint )
            {
                constraint.constrain( *this );
            }

            virtual void
            accept( DraggerCallback& callback )
            {
                callback.receive( *this );
            }

            virtual MotionCommand*
            createCommandInverse();

            inline void
            setScale( double s )
            {
                _scale = s;
            }

            inline double
            getScale() const
            {
                return _scale;
            }

            inline void
            setScaleCenter( double center )
            {
                _scaleCenter = center;
            }

            inline double
            getScaleCenter() const
            {
                return _scaleCenter;
            }

            /** ReferencePoint is used only for snapping. */
            inline void
            setReferencePoint( double rp )
            {
                _referencePoint = rp;
            }

            inline double
            getReferencePoint() const
            {
                return _referencePoint;
            }

            inline void
            setMinScale( double min )
            {
                _minScale = min;
            }

            inline double
            getMinScale() const
            {
                return _minScale;
            }

            virtual osg::dmat4
            getMotionMatrix() const
            {
                return ( osg::translate( -_scaleCenter, 0.0, 0.0 ) *
                         osg::scale( _scale, 1.0, 1.0 ) *
                         osg::translate( _scaleCenter, 0.0, 0.0 ) );
            }

        protected:

            virtual ~Scale1DCommand();

        private:

            double _scale;
            double _scaleCenter;
            double _referencePoint;
            double _minScale;
    };

    /**
     * Command for 2D scaling.
     */
    class OSGMANIPULATOR_EXPORT Scale2DCommand : public MotionCommand
    {
        public:

            Scale2DCommand();

            virtual void
            accept( const Constraint& constraint )
            {
                constraint.constrain( *this );
            }

            virtual void
            accept( DraggerCallback& callback )
            {
                callback.receive( *this );
            }

            virtual MotionCommand*
            createCommandInverse();

            inline void
            setScale( const osg::dvec2& s )
            {
                _scale = s;
            }

            inline const osg::dvec2&
            getScale() const
            {
                return _scale;
            }

            inline void
            setScaleCenter( const osg::dvec2& center )
            {
                _scaleCenter = center;
            }

            inline const osg::dvec2&
            getScaleCenter() const
            {
                return _scaleCenter;
            }

            /** ReferencePoint is used only for snapping. */
            inline void
            setReferencePoint( const osg::dvec2& rp )
            {
                _referencePoint = rp;
            }

            inline const osg::dvec2&
            getReferencePoint() const
            {
                return _referencePoint;
            }

            inline void
            setMinScale( const osg::dvec2& min )
            {
                _minScale = min;
            }

            inline const osg::dvec2&
            getMinScale() const
            {
                return _minScale;
            }

            virtual osg::dmat4
            getMotionMatrix() const
            {
                return ( osg::translate( -_scaleCenter[0], 0.0, -_scaleCenter[1] ) *
                         osg::scale( _scale[0], 1.0, _scale[1] ) *
                         osg::translate( _scaleCenter[0], 0.0, _scaleCenter[1] ) );
            }

        protected:

            virtual ~Scale2DCommand();

        private:

            osg::dvec2 _scale;
            osg::dvec2 _scaleCenter;
            osg::dvec2 _referencePoint;
            osg::dvec2 _minScale;
    };

    /**
     * Command for uniform 3D scaling.
     */
    class OSGMANIPULATOR_EXPORT ScaleUniformCommand : public MotionCommand
    {
        public:

            ScaleUniformCommand();

            virtual void
            accept( const Constraint& constraint )
            {
                constraint.constrain( *this );
            }

            virtual void
            accept( DraggerCallback& callback )
            {
                callback.receive( *this );
            }

            virtual MotionCommand*
            createCommandInverse();

            inline void
            setScale( double s )
            {
                _scale = s;
            }

            inline double
            getScale() const
            {
                return _scale;
            }

            inline void
            setScaleCenter( const osg::dvec3& center )
            {
                _scaleCenter = center;
            }

            inline const osg::dvec3&
            getScaleCenter() const
            {
                return _scaleCenter;
            }

            virtual osg::dmat4
            getMotionMatrix() const
            {
                return ( osg::translate( -_scaleCenter ) *
                         osg::scale( _scale, _scale, _scale ) *
                         osg::translate( _scaleCenter ) );
            }

        protected:

            virtual ~ScaleUniformCommand();

        private:

            double     _scale;
            osg::dvec3 _scaleCenter;
    };

    /**
     * Command for rotation in 3D.
     */
    class OSGMANIPULATOR_EXPORT Rotate3DCommand : public MotionCommand
    {
        public:

            Rotate3DCommand();

            virtual void
            accept( const Constraint& constraint )
            {
                constraint.constrain( *this );
            }

            virtual void
            accept( DraggerCallback& callback )
            {
                callback.receive( *this );
            }

            virtual MotionCommand*
            createCommandInverse();

            inline void
            setRotation( const osg::quat& rotation )
            {
                _rotation = rotation;
            }

            inline const osg::quat&
            getRotation() const
            {
                return _rotation;
            }

            virtual osg::dmat4
            getMotionMatrix() const
            {
                return osg::rotate( osg::dquat( _rotation ) );
            }

        protected:

            virtual ~Rotate3DCommand();

        private:

            osg::quat _rotation;
    };

}
