/* OSGiliath — OpenSceneGraph fork. See LICENSE.txt.
 * Meta-manipulator that switches between numbered manipulators
 * via keyboard keys (1-9). Manages a collection of sub-manipulators.
 */
#pragma once

#include <osgGA/events/GUIEventHandler.hpp>
#include <osgGA/Export>
#include <osgGA/manipulators/CameraManipulator.hpp>

namespace osgGA
{

    class GUIActionAdapter;

    /**
    KeySwitchMatrixManipulator is a decorator which allows the type of camera manipulator
    being used to be switched by pressing a key. E.g. '1' for a TrackballManipulator,
    '2' for a DriveManipulator, '3' for a FlightManipulator. The manipulators available,
    and the associated switch keys, can be configured.
    */
    class OSGGA_EXPORT KeySwitchMatrixManipulator : public CameraManipulator
    {
        public:

            typedef std::pair<std::string, osg::ref_ptr<CameraManipulator>>
                                                    NamedManipulator;
            typedef std::map<int, NamedManipulator> KeyManipMap;

            const char*
            className() const override
            {
                return "KeySwitchMatrixManipulator";
            }

            /**
            Add a camera manipulator with an associated name, and a key to
            trigger the switch,
            */
            void
            addMatrixManipulator( int                key,
                                  std::string        name,
                                  CameraManipulator* cm );

            /**
            Add a camera manipulator with an autogenerated keybinding which is '1' +
            previous number of camera's registered.
            */
            void
            addNumberedMatrixManipulator( CameraManipulator* cm );

            unsigned int
            getNumMatrixManipulators() const
            {
                return static_cast<unsigned int>( _manips.size() );
            }

            void
            selectMatrixManipulator( unsigned int num );

            /** Get the complete list of manipulators attached to this keyswitch
             * manipulator.*/
            KeyManipMap&
            getKeyManipMap()
            {
                return _manips;
            }

            /** Get the const complete list of manipulators attached to this keyswitch
             * manipulator.*/
            const KeyManipMap&
            getKeyManipMap() const
            {
                return _manips;
            }

            /** Get the current active manipulators.*/
            CameraManipulator*
            getCurrentMatrixManipulator()
            {
                return _current.get();
            }

            /** Get the const current active manipulators.*/
            const CameraManipulator*
            getCurrentMatrixManipulator() const
            {
                return _current.get();
            }

            /** Get manipulator assigned to a specified index.*/
            CameraManipulator*
            getMatrixManipulatorWithIndex( unsigned int key );

            /** Get const manipulator assigned to a specified index.*/
            const CameraManipulator*
            getMatrixManipulatorWithIndex( unsigned int key ) const;

            /** Get manipulator assigned to a specified key.*/
            CameraManipulator*
            getMatrixManipulatorWithKey( unsigned int key );

            /** Get const manipulator assigned to a specified key.*/
            const CameraManipulator*
            getMatrixManipulatorWithKey( unsigned int key ) const;

            // Overrides from CameraManipulator...

            /** set the coordinate frame which callback tells the manipulator which way
             * is up, east and north.*/
            void
            setCoordinateFrameCallback( CoordinateFrameCallback* cb ) override;

            /** Set the position of the matrix manipulator using a 4x4 dmat4.*/
            void
            setByMatrix( const osg::dmat4& matrix ) override
            {
                _current->setByMatrix( matrix );
            }

            /** set the position of the matrix manipulator using a 4x4 dmat4.*/
            void
            setByInverseMatrix( const osg::dmat4& matrix ) override
            {
                _current->setByInverseMatrix( matrix );
            }

            /** get the position of the manipulator as 4x4 dmat4.*/
            osg::dmat4
            getMatrix() const override
            {
                return _current->getMatrix();
            }

            /** get the position of the manipulator as a inverse matrix of the
             * manipulator, typically used as a model view matrix.*/
            osg::dmat4
            getInverseMatrix() const override
            {
                return _current->getInverseMatrix();
            }

            /** Get the FusionDistanceMode. Used by SceneView for setting up stereo
             * convergence.*/
            osgUtil::SceneView::FusionDistanceMode
            getFusionDistanceMode() const override
            {
                return _current->getFusionDistanceMode();
            }

            /** Get the FusionDistanceValue. Used by SceneView for setting up stereo
             * convergence.*/
            float
            getFusionDistanceValue() const override
            {
                return _current->getFusionDistanceValue();
            }

            void
            setNode( osg::Node* n ) override;

            const osg::Node*
            getNode() const override
            {
                return _current->getNode();
            }

            osg::Node*
            getNode() override
            {
                return _current->getNode();
            }

            void
            setHomePosition( const osg::dvec3& eye,
                             const osg::dvec3& center,
                             const osg::dvec3& up,
                             bool autoComputeHomePosition = false ) override;

            void
            setAutoComputeHomePosition( bool flag ) override;

            void
            computeHomePosition( const osg::Camera* camera         = nullptr,
                                 bool               useBoundingBox = false ) override;

            void
            finishAnimation() override;

            void
            home( const GUIEventAdapter& ee,
                  GUIActionAdapter&      aa ) override;

            void
            init( const GUIEventAdapter& ee,
                  GUIActionAdapter&      aa ) override
            {
                if( _current.valid() )
                {
                    _current->init( ee, aa );
                }
            }

            bool
            handle( const GUIEventAdapter& ea,
                    GUIActionAdapter&      us ) override;

            /** Get the keyboard and mouse usage of this manipulator.*/
            void
            getUsage( osg::ApplicationUsage& usage ) const override;

        private:

            KeyManipMap                     _manips;

            osg::ref_ptr<CameraManipulator> _current;
    };

}
