char volume_vert[] = "#version 460 core\n"
                     "layout(location = 0) in vec4 osg_Vertex;\n"
                     "uniform mat4 osg_ModelViewMatrixInverse;\n"
                     "uniform mat4 osg_ModelViewProjectionMatrix;\n"
                     "out vec4 cameraPos;\n"
                     "out vec4 vertexPos;\n"
                     "out vec3 lightDirection;\n"
                     "out mat4 texgen;\n"
                     "out vec4 baseColor;\n"
                     "\n"
                     "struct osg_LightSourceParameters {\n"
                     "    vec4 ambient;\n"
                     "    vec4 diffuse;\n"
                     "    vec4 specular;\n"
                     "    vec4 position;\n"
                     "    vec3 spotDirection;\n"
                     "    float spotExponent;\n"
                     "    float spotCutoff;\n"
                     "    float spotCosCutoff;\n"
                     "    float constantAttenuation;\n"
                     "    float linearAttenuation;\n"
                     "    float quadraticAttenuation;\n"
                     "};\n"
                     "uniform osg_LightSourceParameters osg_LightSource;\n"
                     "\n"
                     "struct osg_MaterialParameters {\n"
                     "    vec4 ambient;\n"
                     "    vec4 diffuse;\n"
                     "    vec4 specular;\n"
                     "    vec4 emission;\n"
                     "    float shininess;\n"
                     "};\n"
                     "uniform osg_MaterialParameters osg_FrontMaterial;\n"
                     "\n"
                     "uniform vec4 texgenPlaneS;\n"
                     "uniform vec4 texgenPlaneT;\n"
                     "uniform vec4 texgenPlaneR;\n"
                     "uniform vec4 texgenPlaneQ;\n"
                     "\n"
                     "void main(void)\n"
                     "{\n"
                     "        gl_Position = osg_ModelViewProjectionMatrix * osg_Vertex;\n"
                     "\n"
                     "        cameraPos = osg_ModelViewMatrixInverse * vec4(0,0,0,1);\n"
                     "        vertexPos = osg_Vertex;\n"
                     "        baseColor = osg_FrontMaterial.diffuse;\n"
                     "\n"
                     "        vec4 lightPosition = osg_ModelViewMatrixInverse * osg_LightSource.position;\n"
                     "        if (lightPosition[3]==0.0)\n"
                     "        {\n"
                     "            // directional light source\n"
                     "            lightDirection = -normalize(lightPosition.xyz);\n"
                     "        }\n"
                     "        else\n"
                     "        {\n"
                     "            // positional light source\n"
                     "            lightDirection = normalize((lightPosition-vertexPos).xyz);\n"
                     "        }\n"
                     "\n"
                     "\n"
                     "        texgen = mat4(texgenPlaneS,\n"
                     "                      texgenPlaneT,\n"
                     "                      texgenPlaneR,\n"
                     "                      texgenPlaneQ);\n"
                     "}\n"
                     "\n";
