char volume_multipass_vert[] = "#version 460 core\n"
                               "layout(location = 0) in vec4 osg_Vertex;\n"
                               "uniform mat4 osg_ModelViewMatrixInverse;\n"
                               "uniform mat4 osg_ModelViewProjectionMatrix;\n"
                               "uniform mat4 osg_ProjectionMatrix;\n"
                               "uniform mat4 osg_ProjectionMatrixInverse;\n"
                               "\n"
                               "uniform mat4 eyeToTile;\n"
                               "uniform mat4 tileToImage;\n"
                               "\n"
                               "out vec4 vertexPos;\n"
                               "out vec3 lightDirection;\n"
                               "out vec4 baseColor;\n"
                               "\n"
                               "out mat4 texgen_eyeToTile;\n"
                               "\n"
                               "out float near;\n"
                               "out float far;\n"
                               "out float near_mult_far;\n"
                               "out float far_sub_near;\n"
                               "\n"
                               "struct osg_LightSourceParameters {\n"
                               "    vec4 ambient;\n"
                               "    vec4 diffuse;\n"
                               "    vec4 specular;\n"
                               "    vec4 position;\n"
                               "    vec3 spotDirection;\n"
                               "    float spotExponent;\n"
                               "    float spotCutoff;\n"
                               "    float spotCosCutoff;\n"
                               "    float constantAttenuation;\n"
                               "    float linearAttenuation;\n"
                               "    float quadraticAttenuation;\n"
                               "};\n"
                               "uniform osg_LightSourceParameters osg_LightSource;\n"
                               "\n"
                               "struct osg_MaterialParameters {\n"
                               "    vec4 ambient;\n"
                               "    vec4 diffuse;\n"
                               "    vec4 specular;\n"
                               "    vec4 emission;\n"
                               "    float shininess;\n"
                               "};\n"
                               "uniform osg_MaterialParameters osg_FrontMaterial;\n"
                               "\n"
                               "void main(void)\n"
                               "{\n"
                               "    // compute near and far values from projection matrix.\n"
                               "    near = osg_ProjectionMatrix[2][3] / (osg_ProjectionMatrix[2][2]-1.0);\n"
                               "    far = osg_ProjectionMatrix[2][3] / (1.0+osg_ProjectionMatrix[2][2]);\n"
                               "\n"
                               "    near_mult_far = near*far;\n"
                               "    far_sub_near = far-near;\n"
                               "\n"
                               "    gl_Position = osg_ModelViewProjectionMatrix * osg_Vertex;\n"
                               "\n"
                               "    vertexPos = osg_Vertex;\n"
                               "    baseColor = osg_FrontMaterial.diffuse;\n"
                               "\n"
                               "    vec4 lightPosition = osg_ModelViewMatrixInverse * osg_LightSource.position;\n"
                               "    if (lightPosition[3]==0.0)\n"
                               "    {\n"
                               "        // directional light source\n"
                               "        lightDirection = -normalize(lightPosition.xyz);\n"
                               "    }\n"
                               "    else\n"
                               "    {\n"
                               "        // positional light source\n"
                               "        lightDirection = normalize((lightPosition-vertexPos).xyz);\n"
                               "    }\n"
                               "\n"
                               "    texgen_eyeToTile =  eyeToTile * osg_ProjectionMatrixInverse;\n"
                               "}\n"
                               "\n";
