char shaderpipeline_vert[] =
    "#version 460 core\n"
    "#ifdef GL_ES\n"
    "    precision highp float;\n"
    "    precision highp int;\n"
    "#endif\n"
    "\n"
    "layout(location = 0) in vec4 osg_Vertex;\n"
    "layout(location = 2) in vec3 osg_Normal;\n"
    "layout(location = 3) in vec4 osg_Color;\n"
    "uniform mat4 osg_ModelViewProjectionMatrix;\n"
    "uniform mat4 osg_ModelViewMatrix;\n"
    "uniform mat3 osg_NormalMatrix;\n"
    "\n"
    "#pragma import_defines ( OSG_MAX_TEXTURE_UNITS )\n"
    "#pragma import_defines ( TEXTURE_VERT_DECLARE0, TEXTURE_VERT_BODY0 )\n"
    "#pragma import_defines ( TEXTURE_VERT_DECLARE1, TEXTURE_VERT_BODY1 )\n"
    "#pragma import_defines ( TEXTURE_VERT_DECLARE2, TEXTURE_VERT_BODY2 )\n"
    "#pragma import_defines ( TEXTURE_VERT_DECLARE3, TEXTURE_VERT_BODY3 )\n"
    "\n"
    "#if OSG_MAX_TEXTURE_UNITS>0\n"
    "\n"
    "layout(location = 8) in vec4 osg_MultiTexCoord0;\n"
    "#if OSG_MAX_TEXTURE_UNITS>1\n"
    "layout(location = 9) in vec4 osg_MultiTexCoord1;\n"
    "#endif\n"
    "#if OSG_MAX_TEXTURE_UNITS>2\n"
    "layout(location = 10) in vec4 osg_MultiTexCoord2;\n"
    "#endif\n"
    "#if OSG_MAX_TEXTURE_UNITS>3\n"
    "layout(location = 11) in vec4 osg_MultiTexCoord3;\n"
    "#endif\n"
    "\n"
    "uniform bool OSG_ACTIVE_TEXTURE[OSG_MAX_TEXTURE_UNITS];\n"
    "\n"
    "#ifdef TEXTURE_VERT_DECLARE0\n"
    "    TEXTURE_VERT_DECLARE0\n"
    "#endif\n"
    "#ifdef TEXTURE_VERT_DECLARE1\n"
    "    TEXTURE_VERT_DECLARE1\n"
    "#endif\n"
    "#ifdef TEXTURE_VERT_DECLARE2\n"
    "    TEXTURE_VERT_DECLARE2\n"
    "#endif\n"
    "#ifdef TEXTURE_VERT_DECLARE3\n"
    "    TEXTURE_VERT_DECLARE3\n"
    "#endif\n"
    "\n"
    "#endif\n"
    "\n"
    "out vec3 v_normal;\n"
    "out vec3 v_position;\n"
    "out vec4 v_color;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    v_color = osg_Color;\n"
    "    v_normal = osg_NormalMatrix * osg_Normal;\n"
    "    v_position = (osg_ModelViewMatrix * osg_Vertex).xyz;\n"
    "\n"
    "#if OSG_MAX_TEXTURE_UNITS>0\n"
    "    #ifdef TEXTURE_VERT_BODY0\n"
    "        TEXTURE_VERT_BODY0\n"
    "    #endif\n"
    "    #ifdef TEXTURE_VERT_BODY1\n"
    "        TEXTURE_VERT_BODY1\n"
    "    #endif\n"
    "    #ifdef TEXTURE_VERT_BODY2\n"
    "        TEXTURE_VERT_BODY2\n"
    "    #endif\n"
    "    #ifdef TEXTURE_VERT_BODY3\n"
    "        TEXTURE_VERT_BODY3\n"
    "    #endif\n"
    "#endif\n"
    "\n"
    "    gl_Position = osg_ModelViewProjectionMatrix * osg_Vertex;\n"
    "}\n";
