char shaderpipeline_vert[] = "#version 460 core\n"
                             "#ifdef GL_ES\n"
                             "    precision highp float;\n"
                             "    precision highp int;\n"
                             "#endif\n"
                             "\n"
                             "layout(location = 0) in vec4 osg_Vertex;\n"
                             "layout(location = 2) in vec3 osg_Normal;\n"
                             "layout(location = 3) in vec4 osg_Color;\n"
                             "uniform mat4 osg_ModelViewProjectionMatrix;\n"
                             "uniform mat4 osg_ModelViewMatrix;\n"
                             "uniform mat3 osg_NormalMatrix;\n"
                             "\n"
                             "#pragma import_modes ( OSG_LIGHTING, OSG_LIGHT0)\n"
                             "#pragma import_defines ( OSG_MAX_TEXTURE_UNITS )\n"
                             "#pragma import_defines ( TEXTURE_VERT_DECLARE0, TEXTURE_VERT_BODY0 )\n"
                             "#pragma import_defines ( TEXTURE_VERT_DECLARE1, TEXTURE_VERT_BODY1 )\n"
                             "#pragma import_defines ( TEXTURE_VERT_DECLARE2, TEXTURE_VERT_BODY2 )\n"
                             "#pragma import_defines ( TEXTURE_VERT_DECLARE3, TEXTURE_VERT_BODY3 )\n"
                             "\n"
                             "#if OSG_MAX_TEXTURE_UNITS>0\n"
                             "\n"
                             "layout(location = 8) in vec4 osg_MultiTexCoord0;\n"
                             "#if OSG_MAX_TEXTURE_UNITS>1\n"
                             "layout(location = 9) in vec4 osg_MultiTexCoord1;\n"
                             "#endif\n"
                             "#if OSG_MAX_TEXTURE_UNITS>2\n"
                             "layout(location = 10) in vec4 osg_MultiTexCoord2;\n"
                             "#endif\n"
                             "#if OSG_MAX_TEXTURE_UNITS>3\n"
                             "layout(location = 11) in vec4 osg_MultiTexCoord3;\n"
                             "#endif\n"
                             "\n"
                             "uniform bool OSG_ACTIVE_TEXTURE[OSG_MAX_TEXTURE_UNITS];\n"
                             "\n"
                             "#ifdef TEXTURE_VERT_DECLARE0\n"
                             "    TEXTURE_VERT_DECLARE0\n"
                             "#endif\n"
                             "\n"
                             "#ifdef TEXTURE_VERT_DECLARE1\n"
                             "    TEXTURE_VERT_DECLARE1\n"
                             "#endif\n"
                             "\n"
                             "#ifdef TEXTURE_VERT_DECLARE2\n"
                             "    TEXTURE_VERT_DECLARE2\n"
                             "#endif\n"
                             "\n"
                             "#ifdef TEXTURE_VERT_DECLARE3\n"
                             "    TEXTURE_VERT_DECLARE3\n"
                             "#endif\n"
                             "\n"
                             "#endif\n"
                             "\n"
                             "#if OSG_LIGHTING\n"
                             "struct osg_LightSourceParameters {\n"
                             "    vec4 ambient;\n"
                             "    vec4 diffuse;\n"
                             "    vec4 specular;\n"
                             "    vec4 position;\n"
                             "    vec3 spotDirection;\n"
                             "    float spotExponent;\n"
                             "    float spotCutoff;\n"
                             "    float spotCosCutoff;\n"
                             "    float constantAttenuation;\n"
                             "    float linearAttenuation;\n"
                             "    float quadraticAttenuation;\n"
                             "};\n"
                             "uniform osg_LightSourceParameters osg_LightSource;\n"
                             "\n"
                             "struct osg_MaterialParameters {\n"
                             "    vec4 ambient;\n"
                             "    vec4 diffuse;\n"
                             "    vec4 specular;\n"
                             "    vec4 emission;\n"
                             "    float shininess;\n"
                             "};\n"
                             "uniform osg_MaterialParameters osg_FrontMaterial;\n"
                             "uniform float osg_ColorMaterial;\n"
                             "uniform vec4 osg_LightModel_ambient;\n"
                             "#endif\n"
                             "\n"
                             "out vec4 vertex_color;\n"
                             "\n"
                             "void main()\n"
                             "{\n"
                             "    vertex_color = osg_Color;\n"
                             "\n"
                             "#if OSG_LIGHTING\n"
                             "    #if OSG_LIGHT0\n"
                             "        vec3 rawNormal = osg_NormalMatrix * osg_Normal;\n"
                             "        float normalLen = length(rawNormal);\n"
                             "        vec3 eyeVertex = (osg_ModelViewMatrix * osg_Vertex).xyz;\n"
                             "        vec3 L;\n"
                             "        float attenuation = 1.0;\n"
                             "        if (osg_LightSource.position.w == 0.0) {\n"
                             "            L = normalize(osg_LightSource.position.xyz);\n"
                             "        } else {\n"
                             "            vec3 lightDir = osg_LightSource.position.xyz - eyeVertex;\n"
                             "            float d = length(lightDir);\n"
                             "            L = lightDir / d;\n"
                             "            attenuation = 1.0 / (osg_LightSource.constantAttenuation +\n"
                             "                osg_LightSource.linearAttenuation * d +\n"
                             "                osg_LightSource.quadraticAttenuation * d * d);\n"
                             "            if (osg_LightSource.spotCutoff < 180.0) {\n"
                             "                float spotDot = dot(-L, normalize(osg_LightSource.spotDirection));\n"
                             "                if (spotDot >= osg_LightSource.spotCosCutoff)\n"
                             "                    attenuation *= pow(spotDot, osg_LightSource.spotExponent);\n"
                             "                else\n"
                             "                    attenuation = 0.0;\n"
                             "            }\n"
                             "        }\n"
                             "        // When no normal array is provided, osg_Normal is (0,0,0).\n"
                             "        // Use NdotL=1.0 for full illumination matching legacy behavior.\n"
                             "        float NdotL = (normalLen > 0.001)\n"
                             "            ? max(0.0, dot(rawNormal / normalLen, L))\n"
                             "            : 1.0;\n"
                             "        // GL_COLOR_MATERIAL emulation: when active, vertex color replaces material\n"
                             "        vec4 matDiffuse = mix(osg_FrontMaterial.diffuse, osg_Color, osg_ColorMaterial);\n"
                             "        vec4 matAmbient = mix(osg_FrontMaterial.ambient, osg_Color, osg_ColorMaterial);\n"
                             "        vertex_color.rgb = osg_FrontMaterial.emission.rgb +\n"
                             "                           matAmbient.rgb * (osg_LightModel_ambient.rgb + osg_LightSource.ambient.rgb) +\n"
                             "                           attenuation * matDiffuse.rgb * osg_LightSource.diffuse.rgb * NdotL;\n"
                             "        if (normalLen > 0.001) {\n"
                             "            vec3 n = rawNormal / normalLen;\n"
                             "            vec3 V = (osg_LightSource.position.w == 0.0) ? vec3(0.0, 0.0, 1.0) : normalize(-eyeVertex);\n"
                             "            float NdotHV = max(0.0, dot(n, normalize(L + V)));\n"
                             "            if (NdotL > 0.0 && osg_FrontMaterial.shininess > 0.0)\n"
                             "                vertex_color.rgb += attenuation * osg_FrontMaterial.specular.rgb * osg_LightSource.specular.rgb *\n"
                             "                                    pow(NdotHV, osg_FrontMaterial.shininess);\n"
                             "        }\n"
                             "        vertex_color.a = matDiffuse.a;\n"
                             "    #endif\n"
                             "#endif\n"
                             "\n"
                             "// for each active texture unit we need to do the following....\n"
                             "#if OSG_MAX_TEXTURE_UNITS>0\n"
                             "\n"
                             "    #ifdef TEXTURE_VERT_BODY0\n"
                             "        TEXTURE_VERT_BODY0\n"
                             "    #endif\n"
                             "\n"
                             "    #ifdef TEXTURE_VERT_BODY1\n"
                             "        TEXTURE_VERT_BODY1\n"
                             "    #endif\n"
                             "\n"
                             "    #ifdef TEXTURE_VERT_BODY2\n"
                             "        TEXTURE_VERT_BODY2\n"
                             "    #endif\n"
                             "\n"
                             "    #ifdef TEXTURE_VERT_BODY3\n"
                             "        TEXTURE_VERT_BODY3\n"
                             "    #endif\n"
                             "\n"
                             "#endif\n"
                             "\n"
                             "    gl_Position = osg_ModelViewProjectionMatrix * osg_Vertex;\n"
                             "\n"
                             "}\n";
