char shaderpipeline_frag[] =
    "#version 460 core\n"
    "#ifdef GL_ES\n"
    "    precision highp float;\n"
    "#endif\n"
    "\n"
    "#pragma import_defines ( OSG_MAX_TEXTURE_UNITS )\n"
    "#pragma import_defines ( TEXTURE_FRAG_DECLARE0, TEXTURE_FUNCTION0 )\n"
    "#pragma import_defines ( TEXTURE_FRAG_DECLARE1, TEXTURE_FUNCTION1 )\n"
    "#pragma import_defines ( TEXTURE_FRAG_DECLARE2, TEXTURE_FUNCTION2 )\n"
    "#pragma import_defines ( TEXTURE_FRAG_DECLARE3, TEXTURE_FUNCTION3 )\n"
    "\n"
    "#if OSG_MAX_TEXTURE_UNITS>0\n"
    "#ifdef TEXTURE_FRAG_DECLARE0\n"
    "    TEXTURE_FRAG_DECLARE0\n"
    "#endif\n"
    "#ifdef TEXTURE_FRAG_DECLARE1\n"
    "    TEXTURE_FRAG_DECLARE1\n"
    "#endif\n"
    "#ifdef TEXTURE_FRAG_DECLARE2\n"
    "    TEXTURE_FRAG_DECLARE2\n"
    "#endif\n"
    "#ifdef TEXTURE_FRAG_DECLARE3\n"
    "    TEXTURE_FRAG_DECLARE3\n"
    "#endif\n"
    "#endif\n"
    "\n"
    "// Lighting uniforms\n"
    "struct osg_LightSourceParameters {\n"
    "    vec4 ambient;\n"
    "    vec4 diffuse;\n"
    "    vec4 specular;\n"
    "    vec4 position;\n"
    "    vec3 spotDirection;\n"
    "    float spotExponent;\n"
    "    float spotCutoff;\n"
    "    float spotCosCutoff;\n"
    "    float constantAttenuation;\n"
    "    float linearAttenuation;\n"
    "    float quadraticAttenuation;\n"
    "};\n"
    "uniform osg_LightSourceParameters osg_LightSource;\n"
    "\n"
    "struct osg_MaterialParameters {\n"
    "    vec4 ambient;\n"
    "    vec4 diffuse;\n"
    "    vec4 specular;\n"
    "    vec4 emission;\n"
    "    float shininess;\n"
    "};\n"
    "uniform osg_MaterialParameters osg_FrontMaterial;\n"
    "uniform float osg_ColorMaterial;\n"
    "uniform vec4 osg_LightModel_ambient;\n"
    "uniform bool osg_LightingEnabled;\n"
    "\n"
    "in vec3 v_normal;\n"
    "in vec3 v_position;\n"
    "in vec4 v_color;\n"
    "out vec4 osg_FragColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 frag_color = v_color;\n"
    "\n"
    "    float normalLen = length(v_normal);\n"
    "    if (osg_LightingEnabled && normalLen > 0.001) {\n"
    "        vec3 N = v_normal / normalLen;\n"
    "        vec3 L;\n"
    "        float attenuation = 1.0;\n"
    "        if (osg_LightSource.position.w == 0.0) {\n"
    "            L = normalize(osg_LightSource.position.xyz);\n"
    "        } else {\n"
    "            vec3 lightDir = osg_LightSource.position.xyz - v_position;\n"
    "            float d = length(lightDir);\n"
    "            L = lightDir / d;\n"
    "            attenuation = 1.0 / (osg_LightSource.constantAttenuation +\n"
    "                osg_LightSource.linearAttenuation * d +\n"
    "                osg_LightSource.quadraticAttenuation * d * d);\n"
    "            if (osg_LightSource.spotCutoff < 180.0) {\n"
    "                float spotDot = dot(-L, "
    "normalize(osg_LightSource.spotDirection));\n"
    "                if (spotDot >= osg_LightSource.spotCosCutoff)\n"
    "                    attenuation *= pow(spotDot, osg_LightSource.spotExponent);\n"
    "                else\n"
    "                    attenuation = 0.0;\n"
    "            }\n"
    "        }\n"
    "        float NdotL = max(0.0, dot(N, L));\n"
    "        vec4 matDiffuse = mix(osg_FrontMaterial.diffuse, v_color, "
    "osg_ColorMaterial);\n"
    "        vec4 matAmbient = mix(osg_FrontMaterial.ambient, v_color, "
    "osg_ColorMaterial);\n"
    "        frag_color.rgb = osg_FrontMaterial.emission.rgb +\n"
    "                         matAmbient.rgb * (osg_LightModel_ambient.rgb + "
    "osg_LightSource.ambient.rgb) +\n"
    "                         attenuation * matDiffuse.rgb * "
    "osg_LightSource.diffuse.rgb * NdotL;\n"
    "        vec3 V = (osg_LightSource.position.w == 0.0) ? vec3(0.0, 0.0, 1.0) : "
    "normalize(-v_position);\n"
    "        float NdotHV = max(0.0, dot(N, normalize(L + V)));\n"
    "        if (NdotL > 0.0 && osg_FrontMaterial.shininess > 0.0)\n"
    "            frag_color.rgb += attenuation * osg_FrontMaterial.specular.rgb * "
    "osg_LightSource.specular.rgb *\n"
    "                              pow(NdotHV, osg_FrontMaterial.shininess);\n"
    "        frag_color.a = matDiffuse.a;\n"
    "    }\n"
    "\n"
    "#if OSG_MAX_TEXTURE_UNITS>0\n"
    "    #ifdef TEXTURE_FUNCTION0\n"
    "        frag_color *= TEXTURE_FUNCTION0();\n"
    "    #endif\n"
    "    #ifdef TEXTURE_FUNCTION1\n"
    "        frag_color *= TEXTURE_FUNCTION1();\n"
    "    #endif\n"
    "    #ifdef TEXTURE_FUNCTION2\n"
    "        frag_color *= TEXTURE_FUNCTION2();\n"
    "    #endif\n"
    "    #ifdef TEXTURE_FUNCTION3\n"
    "        frag_color *= TEXTURE_FUNCTION3();\n"
    "    #endif\n"
    "#endif\n"
    "\n"
    "    osg_FragColor = frag_color;\n"
    "}\n";
