char shaderpipeline_frag[] = "#version 460 core\n"
                             "#ifdef GL_ES\n"
                             "    precision highp float;\n"
                             "#endif\n"
                             "\n"
                             "#pragma import_modes ( OSG_LIGHTING )\n"
                             "#pragma import_defines ( OSG_MAX_TEXTURE_UNITS, OSG_ALPHA )\n"
                             "\n"
                             "#pragma import_defines ( TEXTURE_FRAG_DECLARE0, TEXTURE_FUNCTION0, TEXTURE_ENV_FUNCTION0 )\n"
                             "#pragma import_defines ( TEXTURE_FRAG_DECLARE1, TEXTURE_FUNCTION1, TEXTURE_ENV_FUNCTION1 )\n"
                             "#pragma import_defines ( TEXTURE_FRAG_DECLARE2, TEXTURE_FUNCTION2, TEXTURE_ENV_FUNCTION2 )\n"
                             "#pragma import_defines ( TEXTURE_FRAG_DECLARE3, TEXTURE_FUNCTION3, TEXTURE_ENV_FUNCTION3 )\n"
                             "\n"
                             "#if OSG_MAX_TEXTURE_UNITS>0\n"
                             "\n"
                             "uniform int osg_TextureFormat[OSG_MAX_TEXTURE_UNITS];\n"
                             "uniform vec4 osg_TextureEnvColor[OSG_MAX_TEXTURE_UNITS];\n"
                             "\n"
                             "vec4 texenv_MODULATE(vec4 color, vec4 texture_color, int unit) { if (osg_TextureFormat[unit]==OSG_ALPHA) return vec4(color.rgb, color.a*texture_color.a); return color*texture_color; }\n"
                             "vec4 texenv_REPLACE(vec4 color, vec4 texture_color, int unit) { if (osg_TextureFormat[unit]==OSG_ALPHA) return vec4(color.rgb, texture_color.a); return texture_color; }\n"
                             "vec4 texenv_DECAL(vec4 color, vec4 texture_color, int unit) { color.rgb = color.rgb * (1.0-texture_color.a) + texture_color.rgb*texture_color.a; return color; }\n"
                             "vec4 texenv_ADD(vec4 color, vec4 texture_color, int unit) { color.rgb = color.rgb + texture_color.rgb; color.a = color.a*texture_color.a; return color; }\n"
                             "vec4 texenv_BLEND(vec4 color, vec4 texture_color, int unit) { color.rgb = color.rgb * (vec3(1.0,1.0,1.0)-texture_color.rgb) + texture_color.rgb * osg_TextureEnvColor[unit].rgb; return color; }\n"
                             "\n"
                             "#ifdef TEXTURE_FRAG_DECLARE0\n"
                             "    TEXTURE_FRAG_DECLARE0\n"
                             "#endif\n"
                             "\n"
                             "#ifdef TEXTURE_FRAG_DECLARE1\n"
                             "    TEXTURE_FRAG_DECLARE1\n"
                             "#endif\n"
                             "\n"
                             "#ifdef TEXTURE_FRAG_DECLARE2\n"
                             "    TEXTURE_FRAG_DECLARE2\n"
                             "#endif\n"
                             "\n"
                             "#ifdef TEXTURE_FRAG_DECLARE3\n"
                             "    TEXTURE_FRAG_DECLARE3\n"
                             "#endif\n"
                             "\n"
                             "#endif\n"
                             "\n"
                             "\n"
                             "in vec4 vertex_color;\n"
                             "out vec4 osg_FragColor;\n"
                             "\n"
                             "void main()\n"
                             "{\n"
                             "    vec4 frag_color = vertex_color;\n"
                             "\n"
                             "#if OSG_MAX_TEXTURE_UNITS>0\n"
                             "    #ifdef TEXTURE_FUNCTION0\n"
                             "        #ifdef TEXTURE_ENV_FUNCTION0\n"
                             "            frag_color = TEXTURE_ENV_FUNCTION0(frag_color, TEXTURE_FUNCTION0(), 0);\n"
                             "        #else\n"
                             "            frag_color = TEXTURE_FUNCTION0();\n"
                             "        #endif\n"
                             "    #endif\n"
                             "\n"
                             "    #ifdef TEXTURE_FUNCTION1\n"
                             "        #ifdef TEXTURE_ENV_FUNCTION1\n"
                             "            frag_color = TEXTURE_ENV_FUNCTION1(frag_color, TEXTURE_FUNCTION1(), 1);\n"
                             "        #else\n"
                             "            frag_color = TEXTURE_FUNCTION1();\n"
                             "        #endif\n"
                             "    #endif\n"
                             "\n"
                             "    #ifdef TEXTURE_FUNCTION2\n"
                             "        #ifdef TEXTURE_ENV_FUNCTION2\n"
                             "            frag_color = TEXTURE_ENV_FUNCTION2(frag_color, TEXTURE_FUNCTION2(), 2);\n"
                             "        #else\n"
                             "            frag_color = TEXTURE_FUNCTION2();\n"
                             "        #endif\n"
                             "    #endif\n"
                             "\n"
                             "    #ifdef TEXTURE_FUNCTION3\n"
                             "        #ifdef TEXTURE_ENV_FUNCTION3\n"
                             "            frag_color = TEXTURE_ENV_FUNCTION3(frag_color, TEXTURE_FUNCTION3(), 3);\n"
                             "        #else\n"
                             "            frag_color = TEXTURE_FUNCTION3();\n"
                             "        #endif\n"
                             "    #endif\n"
                             "\n"
                             "#endif\n"
                             "\n"
                             "    osg_FragColor = frag_color;\n"
                             "}\n"
                             "\n"
                             "\n";
