char osgText_Text_vert[] = "$OSG_GLSL_VERSION\n"
                           "$OSG_PRECISION_FLOAT\n"
                           "\n"
                           "layout(location = 0) in vec4 osg_Vertex;\n"
                           "layout(location = 3) in vec4 osg_Color;\n"
                           "layout(location = 8) in vec4 osg_MultiTexCoord0;\n"
                           "uniform mat4 osg_ModelViewProjectionMatrix;\n"
                           "uniform mat4 osg_ModelViewMatrix;\n"
                           "\n"
                           "$OSG_VARYING_OUT vec2 texCoord;\n"
                           "$OSG_VARYING_OUT vec4 vertexColor;\n"
                           "\n"
                           "void main(void)\n"
                           "{\n"
                           "    gl_Position = osg_ModelViewProjectionMatrix * osg_Vertex;\n"
                           "    texCoord = osg_MultiTexCoord0.xy;\n"
                           "    vertexColor = osg_Color;\n"
                           "\n"
                           "#if !defined(GL_ES) && __VERSION__<140\n"
                           "    gl_ClipVertex = osg_ModelViewMatrix * osg_Vertex;\n"
                           "#endif\n"
                           "}\n"
                           "\n";
